# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

    # @users.each { |user|

    #   puts "{ username: '#{user.username}', fullname: '#{user.fullname}', created_at: Time.now, updated_at: Time.now },"
  
    # }
    # my_opinions = Opinion.all
    # my_opinions.each { |opinion|

    #   puts "{ author_id: #{opinion.author_id}, text: '#{opinion.text}', created_at: Time.now, updated_at: Time.now },"
  
    # }

    # followings = Following.all
    # followings.each { |following|

    #   puts "{ follower_id: #{following.follower_id}, followed_id: #{following.followed_id} },"
  
    # }

User.create!([

  { username: 'Anna', fullname: 'Anna Mihail Santorinaiou', created_at: Time.now, updated_at: Time.now },
  { username: 'Calvin', fullname: 'Calvin Leonard', created_at: Time.now, updated_at: Time.now },
  { username: 'Christin', fullname: 'Christin Lowerwood', created_at: Time.now, updated_at: Time.now },
  { username: 'George', fullname: 'George Volan', created_at: Time.now, updated_at: Time.now },
  { username: 'Harry', fullname: 'Harry Aster', created_at: Time.now, updated_at: Time.now },
  { username: 'Jimmy', fullname: 'Jimmy Mast', created_at: Time.now, updated_at: Time.now },
  { username: 'Joanna', fullname: 'Joanna Peterson', created_at: Time.now, updated_at: Time.now },
  { username: 'John', fullname: 'John Lewisham', created_at: Time.now, updated_at: Time.now },
  { username: 'Joly', fullname: 'Joly Drakas', created_at: Time.now, updated_at: Time.now },
  { username: 'Kiki', fullname: 'Kiki Legaki', created_at: Time.now, updated_at: Time.now },
  { username: 'Lisa', fullname: 'Lisa Greg', created_at: Time.now, updated_at: Time.now },
  { username: 'Margot', fullname: 'Margot Mediterrane', created_at: Time.now, updated_at: Time.now },
  { username: 'Myron', fullname: 'Myron Zacharian', created_at: Time.now, updated_at: Time.now },
  { username: 'Nasia', fullname: 'Nasia Mafyan', created_at: Time.now, updated_at: Time.now },
  { username: 'Paul', fullname: 'Paul Makridis', created_at: Time.now, updated_at: Time.now },
  { username: 'Tamerlan', fullname: 'Tamerlan Theodor Rubinovski', created_at: Time.now, updated_at: Time.now },
  { username: 'Tony', fullname: 'Tony Martin', created_at: Time.now, updated_at: Time.now }

])

Opinion.create!([

  { author_id: 2, text: 'Americans believe the nation is experiencing a crisis of housing affordability, according to a study done on behalf of the National Association of Home Builders. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 2, text: 'The “World” is a pretty broad location, and there might be travel restrictions to/from the UK.', created_at: Time.now, updated_at: Time.now },
  { author_id: 17, text: 'Daniel Craig have sold an apartment in Manhattan’s East Village for $6 million, breaking even on the deal.', created_at: Time.now, updated_at: Time.now },
  { author_id: 2, text: 'A backyard structure was built for utilities and staff accommodation', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'The star attraction for Mr. Martins, an avid car collector, is the new, vitrine-like, single-car garage, which allows him to rotate his collection of some 15 cars and view them from inside the house.', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'They created a sprawling new master suite on the ground floor, with direct access to the relandscaped yard, and they refashioned the top floor’s original three bedrooms and lone bathroom into four en-suite bedrooms for their four daughters. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'Alejandro Rodrigues Martins and his wife, Rita Barata da Rocha, built a single-car garage in the home’s $540,000 renovation to show off their collection', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'Owners can exercise complete control and monitoring over their MinusA2 via accompanying smart device apps, or talk directly to their filter when at home through Alexa-enabled capabilities. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 6, text: 'In addition to capturing and eliminating just about every pollutant that may be lurking in your air, the MinusA2 comes with connected convenience.', created_at: Time.now, updated_at: Time.now },
  { author_id: 6, text: 'If there is absolutely no room for negotiation for you when it comes to air quality, then you’ll want to get the MinusA2 from Rabbit Air.', created_at: Time.now, updated_at: Time.now },
  { author_id: 6, text: 'Auto mode that reads the room`s air quality and gets to work when needed. The LV-PUR131S is no slouch. Its three-stage filtration system (Pre-Filter, HEPA, Activated Carbon) captures pollutants, odors, pollen, dander, spores, allergens, smoke and more. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'A purifier purist will be in paradise with the LV-PUR131S, which allows users to remotely (via app) control all major device functions—down to turning the LED display on and off—and to track filter life in real-time', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'With a robust suite of air sensor monitors, the Airmega can diagnose and report a room’s air quality in real time. Better still, the Airmega gives myriad control options, via an accompanying mobile app, Alexa-enabled voice control or a Smart Mode, which reads the real-time air quality and automatically adjusts fans and filtration as needed. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 5, text: 'If you want to keep tabs on your home’s air quality—and activate your purifier from across the planet—then you may want to invest in the wi-fi-equipped Coway Airmega 400S.', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'Molekule is also adept at looking after itself. While in Auto mode, Molekule will run its 360-degree air capture and purification process on its own, based on your initial inputs, to keep your room full of refreshed air', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'Developer Marks Down Flats As Hong Kong Prices Fall As Hong Kong home prices continue to fall amid political unrest, the area’s largest developer is reducing the prices of a new slate of flats by 25%.', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'For fresh-air fans that are also fond of features, the Levoit LV-PUR131S has you covered.', created_at: Time.now, updated_at: Time.now },
  { author_id: 14, text: 'This polished, portable purifier is able to capture a remarkable range of pollutants, regardless of size—viruses, allergens, dander, fumes, spores, scents, pollen and more—but Molekule doesn’t stop at capture and filtration, its patented PECO process destroys the air-contaminating criminals.', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'Does it feel a bit stuffy at home? Like you`ve been breathing the same air for a month straight? ', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'Restaurants that survived the coronavirus hit in March and April are reeling from a second punch that could put more eateries out of business.', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'Top officials in southern and western U.S. cities and states with growing coronavirus cases sounded the alarm Sunday, saying hospitals were near capacity and that stricter social-distancing enforcement was needed to stem the growing outbreaks.', created_at: Time.now, updated_at: Time.now },
  { author_id: 10, text: 'Investment consulting firm Aksia LLC has fired a warning shot to hedge-fund and private-equity firms: Don’t take advantage of the federal government’s $350 billion small business loan program or there will be consequences.', created_at: Time.now, updated_at: Time.now },
  { author_id: 8, text: 'Private-equity firm General Atlantic is teaming up with veteran credit investor Tripp Smith to launch a roughly $5 billion fund that will provide financing to companies hit by the new coronavirus pandemic, according to people familiar with the matter.', created_at: Time.now, updated_at: Time.now },
  { author_id: 12, text: 'Carey and Nancy Smith toured 41 New York City homes before finally agreeing this spring to pay almost $20 million for a Greenwich Village townhouse once owned by Malcolm Forbes. Their real-estate agent kept count.', created_at: Time.now, updated_at: Time.now },
  { author_id: 13, text: 'The founders of Big Ass Fans have purchased property belonging to prominent names like Malcolm Forbes and Lance Armstrong. But finding homes that fit the bill was anything but a breeze', created_at: Time.now, updated_at: Time.now },
  { author_id: 5, text: 'Talk show host and comedian Ellen DeGeneres and actress Portia de Rossi are flipping their historic house in Montecito, California, for a quick, but potentially large-margin profit. ', created_at: Time.now, updated_at: Time.now },
  { author_id: 5, text: 'Tate is due to close for a month. I was looking forward to seeing Warhol and Kusama this year. H15-steria strikes again.', created_at: Time.now, updated_at: Time.now },
  { author_id: 18, text: 'No. But the situation is changing quickly as H15-steria is taking effect. I guess more people will die from it than Covid-19.', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'Dubai Summer Sales Marked Four-Year High Sales of new Dubai homes hit a four-year high during the typically busy period between June and August.', created_at: Time.now, updated_at: Time.now },
  { author_id: 4, text: 'Are you unsure where to start with antivirus? Don’t worry, we’ve spent days and weeks testing all providers, so that you don’t have to', created_at: Time.now, updated_at: Time.now },
  { author_id: 15, text: 'Your tour begins in central London, where you board a coach destined for three of England’s most popular attractions.', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'If you too hate to be constantly bothered by mosquitoes, flies and their itching bites, this new device is a must-have!', created_at: Time.now, updated_at: Time.now },
  { author_id: 3, text: 'There are so many antivirus providers in the market that specialise in many different things, so it’s hard to say which is perfect for you', created_at: Time.now, updated_at: Time.now },
  { author_id: 16, text: 'Here`s a good list of rooftop bars across London that are reopening this weekend or in the coming weeks', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'The couple spent $4.5 million on one home and sold another for more than $20 million', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'Unless you hire a car, visiting Stonehenge, Bath, and Windsor Castle in one day is next to impossible', created_at: Time.now, updated_at: Time.now },
  { author_id: 10, text: 'We remove posts that do not follow our posting guidelines, and we reserve the right to remove any post for any reason.', created_at: Time.now, updated_at: Time.now },
  { author_id: 11, text: 'This topic has been closed to new posts due to inactivity. We hope you`ll join the conversation by posting to an open topic or starting a new one.', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'Let me say that one of the nicest things about London is the people.', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'We have now been at home up north in Sweden for 5 days since our week in London and we already talk about going back soon.', created_at: Time.now, updated_at: Time.now },
  { author_id: 1, text: 'The coronavirus pandemic is exposing a central flaw in America`s health care system.', created_at: Time.now, updated_at: Time.now }

])

Following.create!([

  { follower_id: 3, followed_id: 1 },
  { follower_id: 3, followed_id: 2 },
  { follower_id: 2, followed_id: 4 },
  { follower_id: 3, followed_id: 4 },
  { follower_id: 3, followed_id: 5 },
  { follower_id: 4, followed_id: 1 },
  { follower_id: 5, followed_id: 1 },
  { follower_id: 3, followed_id: 12 },
  { follower_id: 1, followed_id: 12 },
  { follower_id: 5, followed_id: 18 },
  { follower_id: 5, followed_id: 17 },
  { follower_id: 5, followed_id: 10 },
  { follower_id: 5, followed_id: 9 },
  { follower_id: 5, followed_id: 8 },
  { follower_id: 5, followed_id: 12 },
  { follower_id: 5, followed_id: 16 },
  { follower_id: 5, followed_id: 4 },
  { follower_id: 18, followed_id: 1 },
  { follower_id: 18, followed_id: 8 },
  { follower_id: 18, followed_id: 10 },
  { follower_id: 18, followed_id: 11 },
  { follower_id: 18, followed_id: 12 },
  { follower_id: 14, followed_id: 8 },
  { follower_id: 14, followed_id: 10 },
  { follower_id: 14, followed_id: 13 },
  { follower_id: 14, followed_id: 17 },
  { follower_id: 14, followed_id: 18 },
  { follower_id: 14, followed_id: 16 },
  { follower_id: 10, followed_id: 3 },
  { follower_id: 10, followed_id: 12 },
  { follower_id: 10, followed_id: 16 },
  { follower_id: 10, followed_id: 14 },
  { follower_id: 10, followed_id: 15 },
  { follower_id: 9, followed_id: 15 },
  { follower_id: 9, followed_id: 3 },
  { follower_id: 9, followed_id: 8 },
  { follower_id: 4, followed_id: 5 },
  { follower_id: 4, followed_id: 10 },
  { follower_id: 4, followed_id: 12 },
  { follower_id: 8, followed_id: 12 },
  { follower_id: 8, followed_id: 13 },
  { follower_id: 8, followed_id: 18 },
  { follower_id: 9, followed_id: 5 },
  { follower_id: 9, followed_id: 18 },
  { follower_id: 9, followed_id: 1 },
  { follower_id: 15, followed_id: 1 },
  { follower_id: 15, followed_id: 11 },
  { follower_id: 15, followed_id: 5 },
  { follower_id: 15, followed_id: 18 },
  { follower_id: 15, followed_id: 10 },
  { follower_id: 15, followed_id: 3 },
  { follower_id: 6, followed_id: 16 },
  { follower_id: 6, followed_id: 5 },
  { follower_id: 6, followed_id: 12 },
  { follower_id: 6, followed_id: 9 },
  { follower_id: 6, followed_id: 14 },
  { follower_id: 6, followed_id: 2 },
  { follower_id: 6, followed_id: 1 },
  { follower_id: 6, followed_id: 3 },
  { follower_id: 6, followed_id: 18 },
  { follower_id: 10, followed_id: 6 },
  { follower_id: 10, followed_id: 9 },
  { follower_id: 10, followed_id: 5 },
  { follower_id: 10, followed_id: 1 },
  { follower_id: 10, followed_id: 4 },
  { follower_id: 12, followed_id: 11 },
  { follower_id: 12, followed_id: 3 },
  { follower_id: 12, followed_id: 6 },
  { follower_id: 12, followed_id: 10 },
  { follower_id: 12, followed_id: 4 },
  { follower_id: 10, followed_id: 11 },
  { follower_id: 10, followed_id: 2 },
  { follower_id: 17, followed_id: 6 },
  { follower_id: 17, followed_id: 11 },
  { follower_id: 12, followed_id: 17 },
  { follower_id: 12, followed_id: 16 },
  { follower_id: 1, followed_id: 11 },
  { follower_id: 1, followed_id: 13 },
  { follower_id: 17, followed_id: 9 },
  { follower_id: 17, followed_id: 12 },
  { follower_id: 16, followed_id: 8 },
  { follower_id: 16, followed_id: 12 },
  { follower_id: 16, followed_id: 3 },
  { follower_id: 16, followed_id: 6 },
  { follower_id: 16, followed_id: 9 },
  { follower_id: 16, followed_id: 15 },
  { follower_id: 16, followed_id: 18 },
  { follower_id: 16, followed_id: 13 },
  { follower_id: 13, followed_id: 8 },
  { follower_id: 13, followed_id: 10 },
  { follower_id: 13, followed_id: 9 },
  { follower_id: 11, followed_id: 1 },
  { follower_id: 11, followed_id: 18 },
  { follower_id: 11, followed_id: 9 },
  { follower_id: 11, followed_id: 10 },
  { follower_id: 11, followed_id: 6 },
  { follower_id: 11, followed_id: 5 },
  { follower_id: 11, followed_id: 17 },
  { follower_id: 11, followed_id: 12 },
  { follower_id: 13, followed_id: 6 },
  { follower_id: 13, followed_id: 1 },
  { follower_id: 13, followed_id: 12 },
  { follower_id: 13, followed_id: 14 },
  { follower_id: 13, followed_id: 5 },
  { follower_id: 13, followed_id: 4 },
  { follower_id: 18, followed_id: 14 },
  { follower_id: 18, followed_id: 13 },
  { follower_id: 17, followed_id: 16 },
  { follower_id: 9, followed_id: 4 },
  { follower_id: 9, followed_id: 11 },
  { follower_id: 1, followed_id: 10 },
  { follower_id: 1, followed_id: 16 },
  { follower_id: 1, followed_id: 5 },
  { follower_id: 11, followed_id: 2 },
  { follower_id: 11, followed_id: 15 },
  { follower_id: 11, followed_id: 4 },
  { follower_id: 2, followed_id: 6 },
  { follower_id: 2, followed_id: 16 },
  { follower_id: 2, followed_id: 11 },
  { follower_id: 2, followed_id: 10 },
  { follower_id: 1, followed_id: 2 },
  { follower_id: 1, followed_id: 4 },
  { follower_id: 1, followed_id: 8 },
  { follower_id: 1, followed_id: 18 }

])

Like.create!([

  { user_id: 15, opinion_id: 9 },
  { user_id: 2, opinion_id: 9 },
  { user_id: 16, opinion_id: 50 },
  { user_id: 15, opinion_id: 50 },
  { user_id: 1, opinion_id: 51 },
  { user_id: 17, opinion_id: 50 },
  { user_id: 16, opinion_id: 53 },
  { user_id: 16, opinion_id: 52 },
  { user_id: 16, opinion_id: 12 },
  { user_id: 16, opinion_id: 10 },
  { user_id: 13, opinion_id: 42 },
  { user_id: 13, opinion_id: 51 },
  { user_id: 13, opinion_id: 48 },
  { user_id: 13, opinion_id: 53 },
  { user_id: 13, opinion_id: 52 },
  { user_id: 13, opinion_id: 37 },
  { user_id: 13, opinion_id: 12 },
  { user_id: 13, opinion_id: 31 },
  { user_id: 13, opinion_id: 11 },
  { user_id: 13, opinion_id: 27 },
  { user_id: 13, opinion_id: 34 },
  { user_id: 13, opinion_id: 36 },
  { user_id: 13, opinion_id: 35 },
  { user_id: 13, opinion_id: 22 },
  { user_id: 18, opinion_id: 17 },
  { user_id: 18, opinion_id: 53 },
  { user_id: 18, opinion_id: 51 },
  { user_id: 18, opinion_id: 50 },
  { user_id: 18, opinion_id: 52 },
  { user_id: 18, opinion_id: 37 },
  { user_id: 17, opinion_id: 51 },
  { user_id: 17, opinion_id: 41 },
  { user_id: 17, opinion_id: 11 },
  { user_id: 17, opinion_id: 38 },
  { user_id: 17, opinion_id: 37 },
  { user_id: 9, opinion_id: 36 },
  { user_id: 9, opinion_id: 53 },
  { user_id: 9, opinion_id: 32 },
  { user_id: 9, opinion_id: 51 },
  { user_id: 9, opinion_id: 20 },
  { user_id: 9, opinion_id: 21 },
  { user_id: 9, opinion_id: 10 },
  { user_id: 9, opinion_id: 16 },
  { user_id: 9, opinion_id: 17 },
  { user_id: 9, opinion_id: 9 },
  { user_id: 9, opinion_id: 54 },
  { user_id: 9, opinion_id: 48 },
  { user_id: 9, opinion_id: 45 },
  { user_id: 1, opinion_id: 24 },
  { user_id: 1, opinion_id: 49 },
  { user_id: 1, opinion_id: 52 },
  { user_id: 1, opinion_id: 37 },
  { user_id: 11, opinion_id: 56 },
  { user_id: 11, opinion_id: 55 },
  { user_id: 11, opinion_id: 54 },
  { user_id: 11, opinion_id: 53 },
  { user_id: 11, opinion_id: 47 },
  { user_id: 1, opinion_id: 28 },
  { user_id: 1, opinion_id: 15 },
  { user_id: 1, opinion_id: 42 },
  { user_id: 1, opinion_id: 57 },
  { user_id: 1, opinion_id: 9 },
  { user_id: 1, opinion_id: 25 },
  { user_id: 2, opinion_id: 32 }
  
])


